## 00. PyTorch Fundamentals

Resource notebook = https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using ``torch.Tensor()`` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)

print(f"{scalar.ndim} \n")
print(f"{scalar.item()} \n")

0 

7 



In [ ]:
# Vector
vector = torch.tensor([7, 7])
print(f"{vector} \n")
print(f"{vector.ndim} \n")
print(f"{vector.shape}")

tensor([7, 7]) 

1 

torch.Size([2])


In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
print(f"{MATRIX} \n")
print(f"{MATRIX.ndim} \n")
print(f"{MATRIX[1]} \n")
print(f"{MATRIX.shape}")

tensor([[ 7,  8],
        [ 9, 10]]) 

2 

tensor([ 9, 10]) 

torch.Size([2, 2])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],

                       [[9, 9, 9],
                        [8, 8, 8],
                        [7, 7, 7]]])


print(f"{TENSOR} \n")
print(f"{TENSOR.ndim} \n")
print(f"{TENSOR[1]} \n")
print(f"{TENSOR.shape}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[9, 9, 9],
         [8, 8, 8],
         [7, 7, 7]]]) 

3 

tensor([[9, 9, 9],
        [8, 8, 8],
        [7, 7, 7]]) 

torch.Size([2, 3, 3])


In [ ]:
# TENSOR2 (4x4x4x4)
TENSOR2 = torch.tensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]],

                         [[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]]],

                        [[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]],

                         [[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]]],

                        [[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]],

                         [[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]]],

                        [[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]],

                         [[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12],
                         [13, 14, 15, 16]],

                        [[2, 4, 6, 8],
                         [10, 12, 14, 16],
                         [18, 20, 22, 24],
                         [26, 28, 30, 32,]]]])


print(f"{TENSOR2} \n")
print(f"{TENSOR2.ndim} \n")
print(f"{TENSOR2[1]} \n")
print(f"{TENSOR2.shape}")

tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]],

         [[ 2,  4,  6,  8],
          [10, 12, 14, 16],
          [18, 20, 22, 24],
          [26, 28, 30, 32]],

         [[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]],

         [[ 2,  4,  6,  8],
          [10, 12, 14, 16],
          [18, 20, 22, 24],
          [26, 28, 30, 32]]],


        [[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]],

         [[ 2,  4,  6,  8],
          [10, 12, 14, 16],
          [18, 20, 22, 24],
          [26, 28, 30, 32]],

         [[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]],

         [[ 2,  4,  6,  8],
          [10, 12, 14, 16],
          [18, 20, 22, 24],
          [26, 28, 30, 32]]],


        [[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3 ,4)

random_tensor = torch.rand(3, 4)

print(f"{random_tensor} \n")
print(f"{random_tensor.ndim} \n")
print(f"{random_tensor.shape}")

tensor([[0.2834, 0.3797, 0.5336, 0.3547],
        [0.2771, 0.0435, 0.1284, 0.7454],
        [0.2460, 0.9097, 0.9400, 0.7183]]) 

2 

torch.Size([3, 4])


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, width, color channels (R, G, B)

print(f"{random_image_size_tensor.ndim} \n")
print(f"{random_image_size_tensor.shape}")

3 

torch.Size([224, 224, 3])


### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeroes = torch.zeros(size=(5, 5))

print(f"{zeroes} \n")
print(f"{zeroes.ndim} \n")


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) 

2 



In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(5, 5))
print(f"{ones} \n")
print(f"{ones.ndim} \n")
print(f"{ones.dtype}")

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

2 

torch.float32


### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-12-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Using torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
steps = torch.arange(start=0, end=1000, step=77)

print(f"{one_to_ten}")
print(f"{steps}")

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


In [ ]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)

print(f"{ten_zeroes}")

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float-32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # What datatype the tensor is (e.g. float32 or float16)
                               device=None,  # What device your tensor is on
                               requires_grad=False)  # Whether or not to track gradients with this tensor's operations

print(f"{float_32_tensor}")
print(f"{float_32_tensor.dtype}")

tensor([3., 6., 9.])
torch.float32


In [ ]:
# Converting the Float-32 tensor to a Float-16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
print(f"{float_16_tensor}")
print(f"{float_16_tensor.dtype}")

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [ ]:
# Trying to multiply float tensors
print(float_32_tensor * float_16_tensor)

tensor([ 9., 36., 81.])


In [ ]:
# Int-32 Tensor
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32,
                             device=None,
                             requires_grad=False)

print(f"{int_32_tensor}")
print(f"{int_32_tensor.dtype}")

tensor([3, 6, 9], dtype=torch.int32)
torch.int32


In [ ]:
# Trying to multiply float tensor with int tensor
print(float_32_tensor * int_32_tensor)

tensor([ 9., 36., 81.])


## Getting information from tensors (tensor attributes)

1. Tensors not right datatype: to get datatype from a tensor, you can use `tensor.dtype`

2. Tensors not right shape: to get shape from a tensor, you can use `tensor.shape`

3. Tensors not ont the right device: to get device from a tensor, you can use `tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor, "\n")
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0032, 0.3454, 0.6449, 0.4771],
        [0.7288, 0.9141, 0.1052, 0.6265],
        [0.9660, 0.9344, 0.4783, 0.5749]]) 

Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
# Creating another tensor
rand_tensor = torch.rand([3, 6],
                         dtype=torch.float16,
                         device="cuda",
                         requires_grad=True)

print(f"Data type of tensor: {rand_tensor.dtype}")
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Device of tensor: {rand_tensor.device}")

Data type of tensor: torch.float16
Shape of tensor: torch.Size([3, 6])
Device of tensor: cuda:0


## Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

### Basic Operations

In [ ]:
# Tensor operations using python
tensor = torch.tensor([1, 2, 3])

print(f"Addition: {tensor + 10}")
print(f"Subtraction: {tensor - 10}")
print(f"Multiplication: {tensor * 10}")
print(f"Division: {tensor / 10}")

Addition: tensor([11, 12, 13])
Subtraction: tensor([-9, -8, -7])
Multiplication: tensor([10, 20, 30])
Division: tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# Tensor operations using PyTorch
print(f"Addition: {torch.add(tensor, 10)}")
print(f"Subtraction: {torch.sub(tensor, 10)}")
print(f"Multiplication: {torch.mul(tensor, 10)}")
print(f"Division: {torch.div(tensor, 10)}")

Addition: tensor([11, 12, 13])
Subtraction: tensor([-9, -8, -7])
Multiplication: tensor([10, 20, 30])
Division: tensor([0.1000, 0.2000, 0.3000])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3234, 0.7057, 0.5833],
        [0.3015, 0.5528, 0.5709],
        [0.2109, 0.3499, 0.4086]])

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
%%time
# Matrix multiplication
torch.matmul(tensor, tensor)  # 1 + 4 + 9 = 14

CPU times: user 44 µs, sys: 8 µs, total: 52 µs
Wall time: 54.8 µs


tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.41 ms, sys: 65 µs, total: 1.47 ms
Wall time: 1.93 ms


## One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# torch.matmul(tensor_A, tensor_B)  ## This won't work because the inner dimensions don't match

To fix our tensor shape issues, we can manipulate the sahpe of one of our tensors using **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}\n")  # Transposed using .T
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match\n")
print(f"Output: \n{torch.matmul(tensor_A, tensor_B.T)}\n")
print(f"Output Shape: {torch.matmul(tensor_A, tensor_B.T).shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output: 
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output Shape: torch.Size([3, 3])


### Finding the min , max, mean, sum, etc. (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Finding the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()  # Does not work with int32 (long)

(tensor(45.), tensor(45.))

In [ ]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Finding the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
# Finding the argmax (positional max)
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking, squeezing, and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - returns a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensor on top of each other (vertical stack) or side-by-side (horizontal stack)
- Squeeze - removes all `1` dimension from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute  - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}\n")

# Remove extra dimensions (removes all 1 dimensions) from x_reshaped
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}\n")

# Add an extra dimension with unsqueeze
print(f"Adding 1 dimension to the zeroth dimension: {x_squeezed.unsqueeze(dim=0)}")  # The zeroth dimension is the index 0/first axis, hence [1, 9]
print(f"New shape: {x_squeezed.unsqueeze(dim=0).shape}\n")
print(f"Adding 1 dimension to the first dimension: {x_squeezed.unsqueeze(dim=1)}")  # The first dimension is the index 1/second axis, hence [9, 1]
print(f"New shape: {x_squeezed.unsqueeze(dim=1).shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

Adding 1 dimension to the zeroth dimension: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

Adding 1 dimension to the first dimension: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute = rearranges the dimensions of a target tensor in a specificed order
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 ,1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 0.9999
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(0.9999), tensor(0.9999))

## Indexing (Selecting data from tensors)

Indexing in PyTorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing on the middle bracket
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Indexing on the inner most bracket
x[0, 0, 0]

tensor(2)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, :, 2]

tensor([[3, 6, 9]])

## PytTorch tensors and Numpy

NumPy is a popular scientific Python numerical computing library.

And becasue of this, PyTorch has functionality to interact with it.

- Converting data in NumPy to PyTorch tensor -> torch.from_numpy(nd_array)
- Converting PyTorch tensor to Numpy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)  # NumPy has float64 as default type
tensor = torch.from_numpy(array)  # Torch.tensor has float32 as default type. However,
                                  # converting the numpy array to torch.tensor makes it also float64
array, array.dtype, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor

# When converting between a NumPy array and a tensor, the resulting object will retain the original's data type

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:
`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again -> again...`

To reduce ithe randomness in neural networks and PyTorch comes the concep of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [ ]:
# Create two random tensors

random_tensor_A = torch.rand(3 ,4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7672, 0.6757, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643, 0.0594],
        [0.7099, 0.4250, 0.2709, 0.9295]])
tensor([[0.6115, 0.2234, 0.2469, 0.4761],
        [0.7792, 0.3722, 0.2147, 0.3288],
        [0.1265, 0.6783, 0.8870, 0.0293]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random_seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)  # Need set the seed again, otherwise, it is not the same seed anymore.
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
- https://pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUS (and making faster computations)

GPUs = Faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest = Use google colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options: https://timdettmers.com/category/deep-learning/
3. Use cloud computing - GCP (Google Cloud Platform), AWS (Amazon Workshop), Azure, these services allow you to rent computers on the cloud and access them.

For 2 and 3, PyTorch + GPU drivers (CUDA) takes a little bit of setting up. To do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Mon Apr  7 03:34:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best to practice setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

e.g. run on GPU if available, else default to CPU

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the GPU

In [13]:
# If tensor is on GPU, can't transform it to NumPy (NumPy does not work with the GPU)
tensor_back_on_cpu = tensor_on_gpu.cpu()
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

tensor_back_on_cpu.numpy()

tensor([1, 2, 3]) cpu


array([1, 2, 3])

## Exercises and Extra-curriculum
See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises