# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.0555, 0.9918, 0.0236, 0.4848, 0.7049, 0.6551, 0.4971],
        [0.4695, 0.3021, 0.2877, 0.8314, 0.5649, 0.6875, 0.8482],
        [0.9511, 0.2219, 0.5295, 0.5700, 0.8319, 0.8421, 0.1411],
        [0.6270, 0.6396, 0.0116, 0.3567, 0.9913, 0.3617, 0.3892],
        [0.8474, 0.6272, 0.3050, 0.0915, 0.4598, 0.7373, 0.5246],
        [0.5948, 0.3346, 0.4466, 0.9347, 0.2989, 0.6347, 0.7956],
        [0.5845, 0.1845, 0.1019, 0.5782, 0.7346, 0.2597, 0.7551]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

random_tensor_2 = torch.rand(1, 7)
random_tensor_2_transposed = random_tensor_2.T # Transposing to match inner dimensions (7, 7) (7, 1)

# Perform matrix multiplication
torch.matmul(random_tensor, random_tensor_2_transposed)  # The resulting shape will be the outer dimensions (7, 1)

tensor([[1.5403],
        [2.4251],
        [2.7928],
        [1.7189],
        [1.9858],
        [2.5354],
        [1.8513]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)

# Create two random tensors
random_tensor = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
random_tensor = torch.rand(2, 3).to(device)
random_tensor_2 = torch.rand(2, 3).to(device)

random_tensor, random_tensor_2

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(random_tensor, random_tensor_2.T)
print(result, result.device, result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) cpu torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(result.max())

# Find min
print(result.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(random_tensor_squeezed, random_tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
